### ISSUE TITLE
Hotels API link is not working!

### ISSUE THREAD

**Issue by abdolrhman** [travolic/Back-End-Task#1]
The [API Link](https://api.myjson.com/bins/tl0bp) is not working, please advice,
Also, I could use another API provider, 
for ex: "https://support.travelpayouts.com"
It will take me some time to go through there documentation,

Thank you.

**Comment by soly2014** [comment]
OK you may use whatever you like
We will finally looking at the code

**Comment by AsmaaMohmed2018** [comment]
the same here there is a problem in calling the Api

**Comment by abdolrhman** [comment]
Hi @AsmaaMohmed2018  
All the hotel APIs providers needs payment or subscription or approval, I have spent some time on them,
I have figured out an API, that can do the job, with almost all properties that task requires,
here is it: http://fake-hotel-api.herokuapp.com/api/hotels

I will close the issue, feel free to open it again if you found any problem regard API,
best of luck ^^

**Comment by soly2014** [comment]
wonderful @abdolrhman
